apiVersion: v1
kind: Service
metadata:
  name: svc-spring
spec:
  type: LoadBalancer
  selector:
    app: spring
  ports:
  - port: 80
    targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: pod-spring
      labels:
        app: spring
    spec:
      containers:
      - name: con-spring
        image: ilohas21/spring:10
